import {
  Activity,
  AlertCircle,
  BarChart3,
  Bell,
  Book,
  Box,
  CalendarCheck,
  CheckSquare,
  Clipboard,
  Clock,
  Code,
  CreditCard,
  Database,
  FileText,
  Folder,
  FolderOpen,
  Globe,
  Heart,
  Home,
  Image as ImageIcon,
  Info,
  Key,
  Layers,
  LayoutDashboard,
  List,
  Lock,
  Mail,
  Map,
  MessageSquare,
  Package,
  Palette,
  Phone,
  Route as RouteIcon,
  Scissors,
  Search,
  Settings,
  Shield,
  ShoppingCart,
  Sparkles,
  Star,
  Tag,
  ToolCase,
  TrendingUp,
  Truck,
  Unlock,
  User,
  Users,
  Wallet,
  Wrench,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Registry ikon admin: nama (disimpan di DB) -> komponen lucide. */
export const ADMIN_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  home: Home,
  users: Users,
  user: User,
  shield: Shield,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  route: RouteIcon,
  list: List,
  folder: Folder,
  'folder-open': FolderOpen,
  scissors: Scissors,
  sparkles: Sparkles,
  calendar: CalendarCheck,
  clock: Clock,
  wallet: Wallet,
  credit: CreditCard,
  settings: Settings,
  tool: Wrench,
  toolbox: ToolCase,
  chart: BarChart3,
  trending: TrendingUp,
  file: FileText,
  image: ImageIcon,
  tag: Tag,
  bell: Bell,
  search: Search,
  mail: Mail,
  phone: Phone,
  message: MessageSquare,
  globe: Globe,
  map: Map,
  star: Star,
  heart: Heart,
  info: Info,
  alert: AlertCircle,
  check: CheckSquare,
  clipboard: Clipboard,
  book: Book,
  code: Code,
  layers: Layers,
  box: Box,
  package: Package,
  database: Database,
  palette: Palette,
  cart: ShoppingCart,
  truck: Truck,
  activity: Activity,
};

/** Daftar nama ikon (untuk picker). */
export const ADMIN_ICON_NAMES = Object.keys(ADMIN_ICONS);

export function getAdminIcon(name?: string | null): LucideIcon {
  if (!name) return LayoutDashboard;
  return ADMIN_ICONS[name] ?? LayoutDashboard;
}
